### ISSUE TITLE
Error when mounting LocalSettings.php directely (not LocalSettings.php.template)

### ISSUE THREAD

**Issue by brunetton** [wmde/wikibase-release-pipeline#185]
Hi

I've read in [Upgrading wikibase docker images](https://github.com/wmde/wikibase-release-pipeline/blob/main/docs/topics/upgrading.md#13-mount-your-localsettingsphp-file-in-the-new-container) that it's possible to mount `LocalSettings.php` file like this:

```yaml
services:
  wikibase:
    volumes:
      - /home/user/LocalSettings.php:/var/www/html/LocalSettings.php
```

But doing this leads to errors in `wdqs-updater`:

    wdqs-updater_1     | Caused by: com.fasterxml.jackson.core.JsonParseException: Unexpected character ('<' (code 60)): expected a valid value (number, String, array, object, 'true', 'false' or 'null')

Did I missed something ?

## Details

- [LocalSettings.php](https://github.com/wmde/wikibase-release-pipeline/files/6671980/LocalSettings.php.txt)
- `docker-compose.yaml` took from [here](https://github.com/wmde/wikibase-docker/blob/dc4fd8cae15e72d883165f37694d07ef45c27e84/docker-compose.yml) (pointed out from wikibase-docker [README](https://github.com/wmde/wikibase-docker#docker-compose-example))

Thanks

**Comment by addshore** [comment]
Hi @brunetton 

We accidently left the issue tracker on on this repository, but issues should be tracked on https://phabricator.wikimedia.org
Any chance you could head there creating a ticket with the `#wikibase-release-pipeline` tag?
We will turn this issue tracker off once you manage that & updated needed docs etc.

**Comment by brunetton** [comment]
Thanks for your answer. 

Indeed I've seen in wikibase-docker README that you're using this issue tracker, but it was after I had opened this issue.

I managed to open an issue on phabricator: https://phabricator.wikimedia.org/T285208

But I didn't find any `wikibase-release-pipeline` tag.

See you there ;)
