### ISSUE TITLE
Move loading of Vector skin into LocalSettings.d snippet

### ISSUE THREAD

**Issue by despens** [wmde/wikibase-release-pipeline#191]
The default LocalSettings.php for the docker install [loads the Vector skin](https://github.com/wmde/wikibase-release-pipeline/blob/783b4292d6d901c258102f0993ae377cff28bae4/Docker/build/Wikibase/LocalSettings.php.template#L49).

For users that want to work with another skin, moving this line to a snippet in LocalSettings.d would prevent having to load multiple skins, or having to change the default LocalSettings.php.

**Comment by addshore** [comment]
Hi @despens 

We accidently left the issue tracker on on this repository, but issues should be tracked on https://phabricator.wikimedia.org
Any chance you could head there creating a ticket with the `#wikibase-release-strategy` tag?
We will turn this issue tracker off once you manage that & updated needed docs etc.

**Comment by despens** [comment]
Sure can do that!

Is "release strategy" the right board/tag? I don't have issues with the strategy, just with an implementation detail...

It would be great to have more discoverable project and repo titles, "release pipeline" is hard to understand and "release strategy" sounds like a management process. Don't think folks looking to deploy Wikibase or contribute code would look for such terms or repos.

Putting these unrelated topics in here just because I know the issues for this repo will be disabled soon :wink:

**Comment by addshore** [comment]
Yes this one https://phabricator.wikimedia.org/tag/wikibase_release_strategy/ (for now)

**Comment by addshore** [comment]
Poke @despens

**Comment by despens** [comment]
Finally added to Phabricator at https://phabricator.wikimedia.org/T290311
