### ISSUE TITLE
The specified username "<nowiki>$1</nowiki>" is invalid. Specify a different username.

### ISSUE THREAD

**Issue by zaid13** [wmde/wikibase-release-pipeline#216]
` docker logs example_wikibase_1`

prints

`wait-for-it.sh: waiting 300 seconds for mysql.svc:3306
wait-for-it.sh: mysql.svc:3306 is available after 0 seconds
wait-for-it.sh: waiting 300 seconds for mysql.svc:3306
wait-for-it.sh: mysql.svc:3306 is available after 0 seconds
The specified username "<nowiki>$1</nowiki>" is invalid.`

and restarts again and again , from where can I change username??

**Comment by toban** [comment]
Closing this as it's now a month with now reply
