### ISSUE TITLE
example, image tags

### ISSUE THREAD

**Issue by atomotic** [wmde/wikibase-release-pipeline#232]
what is the policy of image tags used in [example/template.env](https://github.com/wmde/wikibase-release-pipeline/blob/main/example/template.env#L5-L12)?
is it safe to move to `:latest` or use images from [github registry](https://github.com/orgs/wmde/packages?repo_name=wikibase-release-pipeline)?

```
WIKIBASE_IMAGE_NAME=wikibase/wikibase:1.35.2-wmde.1
WDQS_IMAGE_NAME=wikibase/wdqs:0.3.40-wmde.1
WDQS_FRONTEND_IMAGE_NAME=wikibase/wdqs-frontend:wmde.1
ELASTICSEARCH_IMAGE_NAME=wikibase/elasticsearch:6.5.4-wmde.1
WIKIBASE_BUNDLE_IMAGE_NAME=wikibase/wikibase-bundle:1.35.2-wmde.1
QUICKSTATEMENTS_IMAGE_NAME=wikibase/quickstatements:wmde.1
WDQS_PROXY_IMAGE_NAME=wikibase/wdqs-proxy:wmde.1
MYSQL_IMAGE_NAME=mariadb:10.3
```

**Comment by toban** [comment]
Hey,

We've had discussions around the use of latest tag and the decision was made not to use it for now. Using latest has the potential to put the user in a state where they don't really know which version they are running and the goal was to try to make this decision as conscious as possible.

For more info around this decision and the discussion see [ADR-013](https://github.com/wmde/wikibase-release-pipeline/blob/main/docs/adr/0013-docker-latest-tag.md)
