### ISSUE TITLE
How could I access the quick statements and query services?

### ISSUE THREAD

**Issue by phucty** [wmde/wikibase-release-pipeline#238]
Hello, 
I follow this tutorial  `/example` (I did not modify in the .env and yml files) and successfully run the docker of Wikibase instance. 
`docker-compose -f docker-compose.yml -f docker-compose.extra.yml up`

I access Wikibase with: `localhost` --redirect to-> `localhost/wiki/Main_Page`
I could add some properties, and Items manually. 

I would like to add the data automatically (quick statement) to Wikibase instance and run an SPARQL example. 
However, the connections were refused with these ports (I follow the [old tutorial](http://learningwikibase.com/install-wikibase/)). 

```
Accessing your Wikibase instance and the Query Service UI
    Wikibase @ http://localhost:8181
    Query Service UI @ http://localhost:8282
    Query Service Backend (Behind a proxy) @ http://localhost:8989/bigdata/
    Query Service Backend (Direct) @ http://localhost:8999/bigdata/
    Quickstatements @ http://localhost:9191
```
Could you please let me know how to access the Quickstatements and Query services?

Thank you very much.

**Comment by tonyKunchev** [comment]
Hi @phucty 

If you did't made any changes in the `.env` file, the `Quickstatements` service should be accessible at `localhost:8840` and the `Query Service` at `localhost:8834`.

There are environment variables that are passed on to the `docker-composes`, which are showing the actual ports on which the both services are going to be exposed. Check `QUICKSTATEMENTS_PORT` and `WDQS_FRONTEND_PORT` in the `.env` file.

**Comment by phucty** [comment]
Thank @tonyKunchev very much. 
I can access the query services, and quickstatement in the server (localhost domain) now.

However, I could not access them from network. 

For example, my Wikibase instance is running on a server with IP 192.168.0.10
- Wikibase: `192.168.0.10/wiki/Main_Page` (OK)
- Quickstatement: `192.168.0.10:8840` (fail)
- Query: `192.168.0.10:8834` (fail)

Do we have `Wikibase settings `to make these ports could access from network? 

There are some other quick fix such as port forwardings, or nginx, but Wikibase config might be better. 

Thank you very much

**Comment by toban** [comment]
> Thank @tonyKunchev very much. I can access the query services, and quickstatement in the server (localhost domain) now.
> 
> However, I could not access them from network.
> 
> For example, my Wikibase instance is running on a server with IP 192.168.0.10
> 
>     * Wikibase: `192.168.0.10/wiki/Main_Page` (OK)
> 
>     * Quickstatement: `192.168.0.10:8840` (fail)
> 
>     * Query: `192.168.0.10:8834` (fail)
> 
> 
> Do we have `Wikibase settings `to make these ports could access from network?
> 
> There are some other quick fix such as port forwardings, or nginx, but Wikibase config might be better.
> 
> Thank you very much

In the case of quickstatements did you try altering `QUICKSTATEMENTS_HOST` to your desired IP?

I've noticed the wdqs host is still hardcoded in the example, maybe this should change.

**Comment by phucty** [comment]
Thank @toban very much for your suggestion.

The problem was on port restriction in my local server. It was not opened for 8834 and 8840.

It is not the problem of the docker image. 

Thank you very much for your support.
