### ISSUE TITLE
Could not login QuickStatements

### ISSUE THREAD

**Issue by phucty** [wmde/wikibase-release-pipeline#244]
Hi @toban 
Thank you very much for your answer in the issue of "Search by label does not work in the example environment" https://github.com/wmde/wikibase-release-pipeline/issues/233#issuecomment-976740045

I follow the new instruction at [https://github.com/wmde/wikibase-release-pipeline/tree/wmde.1/example](https://github.com/wmde/wikibase-release-pipeline/tree/wmde.1/example)

However, I could not log in quickstatement.

Environment:
- Server: 136.187.101.158 (Ubuntu 20)

Video: 
This is the video of the process [https://youtu.be/2nhpKKLW9j4](https://youtu.be/2nhpKKLW9j4) 

Steps:
1. login server: `ssh phuc@136.187.101.158`
2. clone the repo: `git clone -b wmde.1 https://github.com/wmde/wikibase-release-pipeline.git`
3. go to the example folder: `cd wikibase-release-pipeline/example`
4. copy template.env to .env: `cp template.env .env`
5. Uncomment the extra-install scripts in docker-compose.yml
6. Uncomment MW_ELASTIC_HOST and MW_ELASTIC_PORT in docker-compose.yml
7. Run docker: `sudo docker-compose -f docker-compose.yml -f docker-compose.extra.yml up`

Up to now. I can access
- Wikibase: 136.187.101.158
- Sparql query: 136.187.101.158:8834
- Quick statements: 136.187.101.158:8834 (but I can not login)

8. Apply a new OAuth to get a new key, and token.
9. Add OAUTH_CONSUMER_KEY, OAUTH_CONSUMER_SECRET to the .env file. Modify the wikibase.svc, and quickstatements.svc to my server IP 136.187.101.158

Now,
- Wikibase: 136.187.101.158 (OK)
- Sparql query: 136.187.101.158:8834 (Fail)
- Quick statements: 136.187.101.158:8834 (can not login)

Could you please guide me on how to log in with quick statements. 

Thank you very much for your time and support.

**Comment by toban** [comment]
Hey, i tried this out myself on my home network and it seems one additional hostname might be required for you to do the following configuration:

```
WIKIBASE_HOST=136.187.101.158
QUICKSTATEMENTS_HOST=136.187.101.158
```

And try this version of the example https://github.com/wmde/wikibase-release-pipeline/pull/249

**Comment by toban** [comment]
I would probably restart the containers and dropping the volumes to start fresh and let the oauth configuration be reset.

This would remove any data you have added though.

**Comment by phucty** [comment]
Thank @toban for your guidance.

It work now with the `quickstatements-still-uses-internal-host` branch.

"..restart the containers and dropping the volumes to start fresh" really helpful. 
I should edit the WIKIBASE_HOST, QUICKSTATEMENTS_HOST, and WDQS_FRONTEND_HOST to my server IP at the first run of docker-compose (to get OAUTH_CONSUMER_KEY, and OAUTH_CONSUMER_SECRET). Otherwise, it will be getting errors in the second run. 

Thank you very much. m(_ _)m (*ˊᗜˋ*)/
