### ISSUE TITLE
ElasticSearch Class not found errors

### ISSUE THREAD

**Issue by rchavez-neu** [wmde/wikibase-release-pipeline#258]
I've deployed the Wikibase + the Wikibase extras using the the current docker-compose.yml and docker-compose.extra.yml files from the Examples directory of the repo 
(with the appropriate env modifications for our environment).  All works fine except for ElasticSearch.

I'm seeing the following error in the logs on run of ElasticSearch.sh:

```
+ '[' -z elasticsearch.svc ']'
+ '[' -z 9200 ']'
+ /wait-for-it.sh elasticsearch.svc:9200 -t 300
wait-for-it.sh: waiting 300 seconds for elasticsearch.svc:9200
wait-for-it.sh: elasticsearch.svc:9200 is available after 0 seconds
+ php /var/www/html/extensions/CirrusSearch/maintenance/UpdateSearchIndexConfig.php
indexing namespaces...
Cannot spawn child: CirrusSearch\Maintenance\IndexNamespaces
[b88bcc940916d095e0c2ef5a] [no req]   Error from line 722 of /var/www/html/maintenance/includes/Maintenance.php: Class 'CirrusSearch\Maintenance\IndexNamespaces' not found
Backtrace:
#0 /var/www/html/extensions/CirrusSearch/includes/Maintenance/Maintenance.php(88): Maintenance->runChild(string, NULL)
#1 /var/www/html/extensions/CirrusSearch/maintenance/UpdateSearchIndexConfig.php(53): CirrusSearch\Maintenance\Maintenance->runChild(string)
#2 /var/www/html/maintenance/doMaintenance.php(107): CirrusSearch\Maintenance\UpdateSearchIndexConfig->execute()
#3 /var/www/html/extensions/CirrusSearch/maintenance/UpdateSearchIndexConfig.php(70): require_once(string)
#4 {main}
```
I'm not sure why we're seeing the Class Not Found errors.

elasticsearch.svc:9200 is up and available.

/var/www/html/LocalSettings.d/Elasticsearch.php looks as it should (I think):
 
```
<?php

# ElasticSearch related extensions
wfLoadExtension( 'Elastica' );
wfLoadExtension( 'CirrusSearch' );
wfLoadExtension( 'WikibaseCirrusSearch' );

if ( getenv('MW_ELASTIC_HOST') !== false ) {
    $wgCirrusSearchServers = [ $_ENV['MW_ELASTIC_HOST'] ];
    $wgSearchType = 'CirrusSearch';
    $wgCirrusSearchExtraIndexSettings['index.mapping.total_fields.limit'] = 5000;
    $wgWBCSUseCirrus = true;
}
```

And Special:Version indicates all components are installed:

Product 	Version
MediaWiki 	1.35.2
PHP 	7.3.28 (apache2handler)
MariaDB 	10.3.32-MariaDB-1:10.3.32+maria~focal
ICU 	63.1
Elasticsearch 	6.5.4
Lua 	5.1.5
WikibaseCirrusSearch	0.1.0
CirrusSearch	6.5.4
Elastica	6.1.3

Are there any additional steps or configuration required in the docker compose files for correct configuration of ElasticSearch?  

Thank you!

**Comment by toban** [comment]
Hey, 

what images are you using and what commit of the example?

**Comment by rchavez-neu** [comment]
Hi,

Images are:

## Image Configuration
WIKIBASE_IMAGE_NAME=wikibase/wikibase:1.35.2-wmde.1
WDQS_IMAGE_NAME=wikibase/wdqs:0.3.40-wmde.1
WDQS_FRONTEND_IMAGE_NAME=wikibase/wdqs-frontend:wmde.1
ELASTICSEARCH_IMAGE_NAME=wikibase/elasticsearch:6.5.4-wmde.1
WIKIBASE_BUNDLE_IMAGE_NAME=wikibase/wikibase-bundle:1.35.2-wmde.1
QUICKSTATEMENTS_IMAGE_NAME=wikibase/quickstatements:wmde.1
WDQS_PROXY_IMAGE_NAME=wikibase/wdqs-proxy:wmde.1
MYSQL_IMAGE_NAME=mariadb:10.3

I'm using the current commit of the example docker compose files.

**Comment by rchavez-neu** [comment]
Not sure if this means anything, but looking on the deployed Docker container for wikibase/wikibase-bundle:1.35.2-wmde.1 in the following two directories:

/var/www/html/extensions/CirrusSearch
/var/www/html/extensions/Elastica

comparing the contents of these two directories to the contents of the snapshot .zip files of these two extensions for 1.35 (see, https://www.mediawiki.org/wiki/Extension:CirrusSearch#Installation).

The contents are nearly identical except that for each extension the Docker container directories are missing the "vendor" directory, which contains autoload.php and a bunch of other autoload and Classloader php files.

**Comment by toban** [comment]
> Hi,
> 
> Images are:
> ## Image Configuration
> 
> WIKIBASE_IMAGE_NAME=wikibase/wikibase:1.35.2-wmde.1 WDQS_IMAGE_NAME=wikibase/wdqs:0.3.40-wmde.1 WDQS_FRONTEND_IMAGE_NAME=wikibase/wdqs-frontend:wmde.1 ELASTICSEARCH_IMAGE_NAME=wikibase/elasticsearch:6.5.4-wmde.1 WIKIBASE_BUNDLE_IMAGE_NAME=wikibase/wikibase-bundle:1.35.2-wmde.1 QUICKSTATEMENTS_IMAGE_NAME=wikibase/quickstatements:wmde.1 WDQS_PROXY_IMAGE_NAME=wikibase/wdqs-proxy:wmde.1 MYSQL_IMAGE_NAME=mariadb:10.3
> 
> I'm using the current commit of the example docker compose files.

Hello again,

I've tried running these images with the example on main without any problems. 

1. clone the repo
2. copy template.env to .env
3. update images with the ones you are using
4. start up `docker-compose -f docker-compose.yml -f docker-compse.extra.yml up`

I'm not really sure what could have put you in this state. Have you altered the images or their contents manually some how?

**Comment by toban** [comment]
> Not sure if this means anything, but looking on the deployed Docker container for wikibase/wikibase-bundle:1.35.2-wmde.1 in the following two directories:
> 
> /var/www/html/extensions/CirrusSearch /var/www/html/extensions/Elastica
> 
> comparing the contents of these two directories to the contents of the snapshot .zip files of these two extensions for 1.35 (see, https://www.mediawiki.org/wiki/Extension:CirrusSearch#Installation).
> 
> The contents are nearly identical except that for each extension the Docker container directories are missing the "vendor" directory, which contains autoload.php and a bunch of other autoload and Classloader php files.

Yeah the vendor folder shouldn't be in there. I am able to reproduce the error by just disabling any of the contents of `ElasticSearch.php`, if CirrusSearch isn't loaded at the time of `UpdateSearchIndexConfig.php` gets executed you get exactly this error. However when you say that `Special:Version` shows all of the installed extensions that doesn't make much sense...

**Comment by toban** [comment]
> Not sure if this means anything, but looking on the deployed Docker container for wikibase/wikibase-bundle:1.35.2-wmde.1 in the following two directories:
> 
> /var/www/html/extensions/CirrusSearch /var/www/html/extensions/Elastica
> 
> comparing the contents of these two directories to the contents of the snapshot .zip files of these two extensions for 1.35 (see, https://www.mediawiki.org/wiki/Extension:CirrusSearch#Installation).
> 
> The contents are nearly identical except that for each extension the Docker container directories are missing the "vendor" directory, which contains autoload.php and a bunch of other autoload and Classloader php files.

Yeah the vendor folder shouldn't be in there. I am able to reproduce the error by just disabling any of the contents of `ElasticSearch.php`, if CirrusSearch isn't loaded at the time of `UpdateSearchIndexConfig.php` gets executed you get exactly this error. However when you say that `Special:Version` shows all of the installed extensions that doesn't make much sense...

**Comment by rchavez-neu** [comment]
Agree.  It's a total head scratcher and doesn't make sense.  I haven't modified the images at all and everything seems to be in place.

Question:  I'm not mounting a modified LocalSettings.php file, I'm just letting the deploy process do what it does and use it's own LocalSettings.php file.  

Should I be adding the contents of /var/www/html/LocalSettings.d/Elasticsearch.php to a modified LocalSettings.php file to ensure that these extensions are loaded?

wfLoadExtension( 'Elastica' );
wfLoadExtension( 'CirrusSearch' );
wfLoadExtension( 'WikibaseCirrusSearch' );

I'll also try a completely fresh repo clone and re-deploy to see what happens.

**Comment by rchavez-neu** [comment]
All is working now.  Here's what I did:I cloned a fresh repo, ported over my .env and docker-compose.yml and docker-compose.extra.yml from my previous environment

**Comment by toban** [comment]
> All is working now. Here's what I did: I cloned a fresh repo, ported over my .env and docker-compose.yml and docker-compose.extra.yml from my previous environment
> 
> ElasticSearch was fine on deploy.
> 
> I have no explanation for why ElasticSearch wasn't working with the previous images, but the only thing that really changed were the new images from the template.env file.
> 
> At any rate, all is well. Thank you very much for all your help with this!

Great news! Thanks for reporting back!
