### ISSUE TITLE
Here VS Phabricator?

### ISSUE THREAD

**Issue by shigapov** [wmde/wikibase-release-pipeline#260]
Hi @toban,

I am testing the latest release and have opened two related issues at Phabricator. Should I open the issues here instead of Phabricator?

See
* [T296812 'Add path-variable to template.env in Wikibase Release Pipeline in order to specify the path for volumes'](https://phabricator.wikimedia.org/T296812)
* [T296917 'Customize the word cloud of properties in WDQS Frontend of Wikibase Release Pipeline'](https://phabricator.wikimedia.org/T296917)

and I've added a [comment](https://phabricator.wikimedia.org/T270293#7540438) to [T270293 'Parsing example queries partially produce errors'](https://phabricator.wikimedia.org/T270293).

**Comment by manicki** [comment]
Please do use Phabricator for the issues like those @shigapov

**Comment by shigapov** [comment]
I do @manicki. I was just surprised to see activity in the issues here and not at Phabricator.

**Comment by manicki** [comment]
Thanks. Yes, we're a bit behind on communicating the preferred bug report/etc channels
