### ISSUE TITLE
define WIKIBASE_SCHEME

### ISSUE THREAD

**Issue by D063520** [wmde/wikibase-release-pipeline#280]
As far as I understand the idea is to set all custom variables in the .env file while the docker-compose.yml and docker-compose.extra.yml stay the same. Would it then not be better to move to the /env file also WIKIBASE_SCHEME?

**Comment by toban** [comment]
Yeah this could be done but probably requires a bigger overhaul of some composite env variables, feel free to add this as a feature request on this board https://phabricator.wikimedia.org/project/board/5063/.

**Comment by toban** [comment]
https://phabricator.wikimedia.org/T298077
