### ISSUE TITLE
Many warnings while updating

### ISSUE THREAD

**Issue by D063520** [wmde/wikibase-release-pipeline#281]
While updating from the wikibase-docker repo I get many of these warnings:

elasticsearch_1       | [2021-12-18T23:45:13,133][WARN ][o.e.d.c.ParseField       ] [MLTxyEr] Deprecated field [_retry_on_conflict] used, expected [retry_on_conflict] instead

any idea what this could be?

**Comment by toban** [comment]
Looks like something related to https://github.com/elastic/logstash/issues/9092

**Comment by toban** [comment]
Hopefully we will move away from these old versions of ElasticSearch and use the maintained 6.8.x ones as soon as the wikibase plugins are updated.
