### ISSUE TITLE
Configuration limitations for OAuth between Wikibase and QuickStatements

### ISSUE THREAD

**Issue by jmformenti** [wmde/wikibase-release-pipeline#282]
I've noticed that some settings, in _.env_ file, prevent OAuth authentication from working between Wikibase and QuickStatements, in particular:

1. Use same domain name for Wikibase and QuickStatements, for example:
```
WIKIBASE_HOST=mydomain.svc
WIKIBASE_PORT=80
QUICKSTATEMENTS_HOST=mydomain.svc
QUICKSTATEMENTS_PORT=8840
```
2. For Wikibase use a port other than 80, for example:
```
WIKIBASE_HOST=wikibase.svc
WIKIBASE_PORT=3001
QUICKSTATEMENTS_HOST=quickstatements.svc
QUICKSTATEMENTS_PORT=8840
```

Any idea?

**Comment by toban** [comment]
Hey, 

Setting up Wikibase with Quickstatements via OAuth has always been somewhat of an issue as there are just so many variables to get right and the error reporting from quickstatements leaves a lot more to wish for. Quickstatements was built as a tool for wikidata.org and works best in a configuration that uses external hostnames. Preferably you run the example on a local machine but access it through a hostname over the internet or a different machine on your home network. The test setup used in this repo all communicate through the internal docker network.

To respond to your examples.

1. I don't think this would work as `mydomain.svc` looks like an internal docker hostname. As they aren't running in the same container I don't see how the routing would work there.

2. I would have thought this would work but can't find an example where we have successfully run this kind of configuration, there is a high probability that there is something hard-coded in Quickstatements that doesn't allow this to work. All of our testing + test systems that use Quickstatements are configured with Wikibase running on port 80 so I would advise against it.

When configuring Quickstatements I'd like you to take a look at the environment section of the `quickstatements` service especially these

```
      - WIKIBASE_SCHEME_AND_HOST=http://wikibase-docker.svc
      - QS_PUBLIC_SCHEME_HOST_AND_PORT=http://${QUICKSTATEMENTS_HOST}:${QUICKSTATEMENTS_PORT}
      - WB_PUBLIC_SCHEME_HOST_AND_PORT=http://${WIKIBASE_HOST}:${WIKIBASE_PORT}
```

By default in the example the internal OAuth calls are done in the docker network using `wikibase-docker.svc` which is an alias hostname of the wikibase service. Maybe this could be conflicting with your configuration.

**Comment by jmformenti** [comment]
Thanks @toban

Regarding point 1, I tried to use an public dns name but It seems that doesn't work.

Perhaps `WIKIBASE_SCHEME_AND_HOST` parameter is used internally in QS in some place instead of `WB_PUBLIC_SCHEME_HOST_AND_PORT`.

**Comment by moinluk** [comment]
Did you checked if the extra-installe script worked propery?

The extra_install script should create two files:
`/quickstatements/data/qs-oauth.json` and `/quickstatements/data/oauth.ini`, (`/quickstatements/data/` is mounted from a extra volume which is shared to wikibase and and quickstatements).

Logon to the wikibase container and check if these two files exists.
If not run the extra install script from the wikibase root (`/var/www/html`) otherwise the extra install script would not work properly.

**Comment by jmformenti** [comment]
Yes, confirmed, I have both files.
I think is a limitation, probably for something hardcoded in QuickStatements as toban said.

**Comment by toban** [comment]
Hey, 

I thought i got it working here https://github.com/wmde/wikibase-release-pipeline/pull/289 

But the problem now is that the request to `http://localhost:8840/api.php?action=is_logged_in` returns that im not logged in. However initiating the OAuth handshake seems to work and i'm redirect to Quickstatements afterwards.

Does that sound familiar to you, or was the OAuth sequence more broken?

**Comment by jmformenti** [comment]
Exactly, that's the behaviour that I had. 

Apparently is all working but at the end, Quicstatements is not logged.

**Comment by rchavez-neu** [comment]
Have run into the exact same problem.  Has anyone found a solution since January?

**Comment by darthmon** [comment]
Hi there from the Sweet Team,
Thanks a lot for reporting the error and apologies for not getting it fixed quicker.

Our imminent release solves this issue using a reverse proxy.

I will proceed to close this issue now. I invite you to move to the coming out newest version of WBS. 

Please, reach out if you want support to update or have issues updating :)

Best,
Sweet EM

**Comment by lucamauri** [comment]
> Our imminent release solves this issue using a reverse proxy.

@darthmon can you please elaborate further on how this was fixed, or point to the relevant modified configuration files?
I am trying to make the containerized QS work with an external Wikibase instance, not the one included in WBS, so I am interested in understanding how to fix this in case tho OAuth is performed outside of the WBS.

Thanks in advance.
