### ISSUE TITLE
`An error has occurred while searching` when running Wikibase without Elasticsearch

### ISSUE THREAD

**Issue by persona0591** [wmde/wikibase-release-pipeline#296]
Hi all,

I'm trying to run Wikibase using the (full) [docker-compose.yml](https://github.com/wmde/wikibase-release-pipeline/blob/wmde.3/example/docker-compose.yml) and [docker-compose.extra.yml](https://github.com/wmde/wikibase-release-pipeline/blob/wmde.3/example/docker-compose.extra.yml) example files. This is working perfectly.

However, I don't want to run Elasticsearch. Therefore I've removed the relevant service in [docker-compose.extra.yml](https://github.com/wmde/wikibase-release-pipeline/blob/wmde.3/example/docker-compose.extra.yml#L21-L32) and the relevant part of [extra-install.sh](https://github.com/wmde/wikibase-release-pipeline/blob/wmde.3/example/extra-install.sh#L5).

If I now start Wikibase, add a new item and then search for this item using MediaWiki's search box, the following error is displayed:

`An error has occurred while searching: We could not complete your search due to a temporary problem. Please try again later. ` 

I'm not sure what the cause of this error is. Could it be that Wikibase assumes Elasticsearch is running? If so, how can I change this behavior?

Thank you :)

![search-error](https://user-images.githubusercontent.com/45238553/148901045-6d89560f-e5c3-4bdf-8db9-3a689afa5354.png)

**Comment by ross-spencer** [comment]
Hi George, 

I had the same problem recently and was scratching my head as I thought I had the same config as another server not running Elasticsearch but I found a couple of extra lines of configuration and commented those out too. 

I have copied my config here if it helps you find what you need: 
* https://gist.github.com/ross-spencer/26ee9b999d9e36dcdfca90c107562577

Once the config was in place, IIRC running `sudo docker-compose -f docker-compose.yml -f docker-compose.extra.yml up -d --force-recreate` was enough to fix things for me. 

My config might be a little out of date now, I haven't been able to follow the changes in this repo, but hopefully they haven't diverged too much.

**Comment by persona0591** [comment]
Hi @ross-spencer,

Wow! Your config is indeed a little out of date, but I can clearly see why you've managed to disable Elasticsearch: in `docker-compose-extra.yml` you've commented the lines with the Elasticsearch environment variables:

https://gist.github.com/ross-spencer/26ee9b999d9e36dcdfca90c107562577#file-docker-compose-extra-yml-L9-L10

I've just tried the same in the new [docker-compose-extra.yml](https://github.com/wmde/wikibase-release-pipeline/blob/wmde.3/example/docker-compose.extra.yml#L5-L6) config - and it works: I can use Wikibase's search functionality again.

Problem solved - although this perhaps could be documented a bit better in the example files :)

Thank you very much!

**Comment by ross-spencer** [comment]
Nice, thanks @persona0591, glad it worked! +1 on inspiration for docs. I have a [related hope for the docs](https://www.mediawiki.org/wiki/Topic:Whwk5sby15t2uflz) for a recommendation on Elastic vs. Cirrus and use-cases. It's interesting that Cirrus can satisfy some requirements and should also reduce maintenance complexity.

**Comment by toban** [comment]
Hello,

I've added PR to make this a bit more clear in the template

https://github.com/wmde/wikibase-release-pipeline/pull/299

Thanks @ross-spencer for helping out! :100:

**Comment by persona0591** [comment]
Thank you, @toban!

**Comment by versant2612** [comment]
I've tried this solution to disable the application search error but it didn't worked. 

My extra-install.sh file is a directory ?!?!?!?!?!?!

**Comment by toban** [comment]
> I've tried this solution to disable the application search error but it didn't worked.
> 
> My extra-install.sh file is a directory ?!?!?!?!?!?!

Hey, this sounds like the `extra-install.sh` file might not have been mounted correctly. From my experience if the `extra-install.sh` file is mounted as a directory this probably means the file does not exist on the host machine and docker therefore creates it as a folder instead.

**Comment by versant2612** [comment]
@toban I copied the extra-install.sh from example directory to the installation directory and tried again. But it didn't solved. I do want to use Elastic Search.

**Comment by toban** [comment]
> @toban I copied the extra-install.sh from example directory to the installation directory and tried again. But it didn't solved. I do want to use Elastic Search.

The `extra-install.sh` script is by default located in the same directory as the docker-compose.yml and docker-compose.extra.yml files.

If you check it's mounted by the `docker-compose.extra.yml` file like this
https://github.com/wmde/wikibase-release-pipeline/blob/main/example/docker-compose.extra.yml#L13

```yml
 wikibase:
    volumes:
      - quickstatements-data:/quickstatements/data
      - ./extra-install.sh:/extra-install.sh
```

Could you describe the problem you are having a bit more in detail with some logs and maybe explain what your installation directory contains I think we get get it working.

**Comment by toban** [comment]
> > @toban I copied the extra-install.sh from example directory to the installation directory and tried again. But it didn't solved. I do want to use Elastic Search.
> 
> The `extra-install.sh` script is by default located in the same directory as the docker-compose.yml and docker-compose.extra.yml files.
> 
> If you check it's mounted by the `docker-compose.extra.yml` file like this https://github.com/wmde/wikibase-release-pipeline/blob/main/example/docker-compose.extra.yml#L13
> 
> ```yaml
>  wikibase:
>     volumes:
>       - quickstatements-data:/quickstatements/data
>       - ./extra-install.sh:/extra-install.sh
> ```
> 
> Could you describe the problem you are having a bit more in detail with some logs and maybe explain what your installation directory contains I think we get get it working.

sorry just realized you have another issue open, lets continue in there.
