### ISSUE TITLE
`Contained error syncing` when using `$wgLanguageCode` in LocalSettings.php

### ISSUE THREAD

**Issue by persona0591** [wmde/wikibase-release-pipeline#297]
Hi all,

I'm trying to run Wikibase using the (full) [docker-compose.yml](https://github.com/wmde/wikibase-release-pipeline/blob/wmde.3/example/docker-compose.yml) and [docker-compose.extra.yml](https://github.com/wmde/wikibase-release-pipeline/blob/wmde.3/example/docker-compose.extra.yml) example files. This is working perfectly.

However, I want to add my own LocalSettings.php. It looks like this:

```php
<?php
    $wgLanguageCode = "fr";
?>
```

To make this work, I uncomment the following line in [docker-compose.yml](https://github.com/wmde/wikibase-release-pipeline/blob/main/example/docker-compose.yml#L33):

`./LocalSettings.php:/var/www/html/LocalSettings.d/LocalSettings.override.php`

If I now start Wikibase and add a new item with a French label, the following error from `wdqs-updater_1` is visible in my Docker log output, and the item isn't synced to the WikibaseQueryService:

```
WARN  org.wikidata.query.rdf.tool.Updater - Contained error syncing.  Giving up on Q1
org.wikidata.query.rdf.tool.exception.ContainedException: Didn't get a revision id for [(http://wikibase.svc/entity/Q1, http://www.w3.org/2000/01/rdf-schema#label, "Test1"@fr)]
    at org.wikidata.query.rdf.tool.rdf.Munger$MungeOperation.finishCommon(Munger.java:818)
    at org.wikidata.query.rdf.tool.rdf.Munger$MungeOperation.munge(Munger.java:413)
    at org.wikidata.query.rdf.tool.rdf.Munger.munge(Munger.java:144)
    at org.wikidata.query.rdf.tool.Updater.handleChange(Updater.java:415)
    at org.wikidata.query.rdf.tool.Updater.lambda$fetchDataFromWikibaseAndMunge$7(Updater.java:283)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
    at java.lang.Thread.run(Thread.java:748)
```

If I remove the `$wgLanguageCode` from my `LocalSettings.php`, restart Wikibase and then add a new item again with an English label, the error isn't thrown.

Do you know what could be the cause of this?

Thank you!

**Comment by toban** [comment]
Hey thanks for the report and bringing to our knowledge.

I've confirmed this bug it seems to be a problem with `Special:Entity` data rendering translations incorrectly.

There seems to be an issue reported some time ago https://phabricator.wikimedia.org/T139916 will ask around to see if we can fix this soon seeing how long ago the ticket was reported.

**Comment by toban** [comment]
Rightmost is the french translation being used in the url.

![Image Pasted at 2022-1-12 11-54](https://user-images.githubusercontent.com/352149/149138474-03cb0411-eca1-4e1a-84e9-0f027ac6cd8a.png)

**Comment by persona0591** [comment]
Hi @toban Thank you!
