### ISSUE TITLE
Blazegraph are being killed: runBlazegraph.sh: line 6: 12 Killed  ./runBlazegraph.sh

### ISSUE THREAD

**Issue by marcelomachado** [wmde/wikibase-release-pipeline#298]
I'm trying to build a Wikidata Query Service instance on an Openshift Cluster.  I'm using Docker Images for this.
However, the Pods are getting killed when running Blazegraph and the only message I see is:
`runBlazegraph.sh: line 6: 12 Killed  ./runBlazegraph.sh`.

I also tried to run the example folder in my own computer. However the same error occurs, all services (wdqs-frontend, elasticsearch so on) is running but the wdqs is restarting with the same message: `runBlazegraph.sh: line 6: X Killed  ./runBlazegraph.sh`.

What am I missing?

Thank you in advance

**Comment by toban** [comment]
Hey sounds like this might be a memory issue did you try configuring some of the variables for the docker image?

**Comment by marcelomachado** [comment]
Yes, it is a memory issue. 
In my computer I had to increase the Docker memory. The default installation dedicates 2GB, so I increased to 8GB and everything worked.

In the OpenShift cluster I set the memory in the `resources` section of the container:

```
containers:
  - resources:
       limits:
          memory: 16Gi
       requests:
          memory: 8Gi
