### ISSUE TITLE
Unable to use WDQS: `Bad Gateway`?

### ISSUE THREAD

**Issue by persona0591** [wmde/wikibase-release-pipeline#300]
Hi all,

I'm running Wikibase locally - on my development machine - using the (full) [docker-compose.yml](https://github.com/wmde/wikibase-release-pipeline/blob/wmde.3/example/docker-compose.yml) and [docker-compose.extra.yml](https://github.com/wmde/wikibase-release-pipeline/blob/wmde.3/example/docker-compose.extra.yml) example files. This is working perfectly.

However, I now want to run Wikibase on my external hosting environment, using the same configuration. I've changed the env var `WIKIBASE_HOST` in my [`.env` file](https://github.com/wmde/wikibase-release-pipeline/blob/main/example/template.env#L37) to my public IP address.

If I now start Wikibase a number of errors appear in the container output:

```
wdqs-updater_1        | wait-for-it.sh: waiting 300 seconds for <redacted public IP address>:80
```

and:

```
wdqs_1                | /runBlazegraph.sh: line 6:    11 Killed                  ./runBlazegraph.sh
```

and eventually:

```
wikibase_wdqs_1 exited with code 137
```

As a result, if I go to the query service and execute a SPARQL query there, I get a `502 Bad Gateway` error. The container output:

```
wdqs-proxy_1          | 2022/01/15 06:30:02 [error] 9#9: *3 connect() failed (111: Connection refused) while connecting to upstream, client: 172.21.0.8, server: , request: "GET /bigdata/namespace/wdq/sparql?query=select%20*%0Awhere%20%7B%20%3Fs%20%3Fp%20%3Fo%20%7D HTTP/1.0", upstream: "http://172.21.0.3:9999/bigdata/namespace/wdq/sparql?query=select%20*%0Awhere%20%7B%20%3Fs%20%3Fp%20%3Fo%20%7D", host: "wdqs-proxy.svc"
```

Do you know how to resolve this? For example: was I wrong in using my public IP in the `WIKIBASE_HOST` file - should I use something else?

Thank you!

<img width="935" alt="error" src="https://user-images.githubusercontent.com/45238553/149611414-e1496068-87c9-4ac0-af78-99985ee10b66.png">

**Comment by persona0591** [comment]
Hi all,

Following up on my previous question: I've replaced my public IP address in my `.env` file (based on [template.env](https://github.com/wmde/wikibase-release-pipeline/blob/main/example/template.env#L37)) with my public hostname.

The issue still remains, unfortunately: if I send a SPARQL query, via the WDQS, to the triple store, a `502 Bad Gateway` is returned.

In the Docker log output I see messages like:

`wdqs-updater_1        | 16:57:59.547 [main] INFO  o.w.query.rdf.tool.HttpClientUtils - HTTP request failed: java.util.concurrent.ExecutionException: java.net.ConnectException: Connection refused, attempt 6, will fail`

Has anyone found a way to get Wikibase running on a non-development environment? For example: do I need to make additional changes to the [docker-compose.yml](https://github.com/wmde/wikibase-release-pipeline/blob/wmde.3/example/docker-compose.yml) and [docker-compose.extra.yml](https://github.com/wmde/wikibase-release-pipeline/blob/wmde.3/example/docker-compose.extra.yml) example files?

**Comment by toban** [comment]
Hey,

I have never tried using the Public IP in the full setup but running it with a hostname should work.

This is how the configuration of our test-system looks.

```

## Wikibase Configuration
WIKIBASE_PINGBACK=false
WIKIBASE_HOST=wikibase-product-testing.wmflabs.org
WIKIBASE_PORT=80

## WDQS-frontend Configuration
WDQS_FRONTEND_HOST=wikibase-query-testing.wmflabs.org
WDQS_FRONTEND_PORT=8834

# Quickstatements Configuration
QUICKSTATEMENTS_HOST=wikibase-qs-testing.wmflabs.org
QUICKSTATEMENTS_PORT=8840

## ElasticSearch
MW_ELASTIC_HOST=elasticsearch.svc
MW_ELASTIC_PORT=9200
``` 

I vaguely remember seeing that bad gateway once and it was resolved by restarting the container.

**Comment by persona0591** [comment]
Thanks, @toban!

I wasn't aware that `WDQS_FRONTEND_HOST` could/should also be changed. The [example file](https://github.com/wmde/wikibase-release-pipeline/blob/main/example/template.env#L41) says that [`WIKIBASE_HOST`](https://github.com/wmde/wikibase-release-pipeline/blob/main/example/template.env#L36) and [`QUICKSTATEMENTS_HOST`](https://github.com/wmde/wikibase-release-pipeline/blob/main/example/template.env#L45) should be changed, but this comment isn't there for `WDQS_FRONTEND_HOST`.

**Comment by toban** [comment]
> Thanks, @toban!
> 
> I wasn't aware that `WDQS_FRONTEND_HOST` could/should also be changed. The [example file](https://github.com/wmde/wikibase-release-pipeline/blob/main/example/template.env#L41) says that [`WIKIBASE_HOST`](https://github.com/wmde/wikibase-release-pipeline/blob/main/example/template.env#L36) and [`QUICKSTATEMENTS_HOST`](https://github.com/wmde/wikibase-release-pipeline/blob/main/example/template.env#L45) should be changed, but this comment isn't there for `WDQS_FRONTEND_HOST`.

Updated the template with the comment. Thanks for pointing that out.

Yeah it has been added later on. Ideally have a peek around the docker-compose.yml and docker-compose.extra.yml if you decide to use this example. It's not really a production ready thing and just serves as an example on how this could be configured with the images.

**Comment by persona0591** [comment]
Thanks, @toban! Also for pointing out that the examples aren't production-ready. Perhaps this could also be mentioned in the [README.md](https://github.com/wmde/wikibase-release-pipeline/blob/main/example/README.md)?

**Comment by toban** [comment]
> Thanks, @toban! Also for pointing out that the examples aren't production-ready. Perhaps this could also be mentioned in the [README.md](https://github.com/wmde/wikibase-release-pipeline/blob/main/example/README.md)?

good idea https://github.com/wmde/wikibase-release-pipeline/pull/301/files
