### ISSUE TITLE
How could we customize the query examples of WDQS-frontend?

### ISSUE THREAD

**Issue by phucty** [wmde/wikibase-release-pipeline#309]
Hi there,
How could we customize the query examples of WDQS-frontend?

The default query examples are difficult to use in my local Wikibase instance since QID and PID total difference compared to Wikidata.

Could you please let me know how to customize these examples (remove default examples, and add appropriate query examples as my local instance)?

Thank you very much.
Regards.

**Comment by addshore** [comment]
Right now it looks like the example server in the docker containers is still pointing to wikidata
https://github.com/wmde/wikibase-release-pipeline/blob/main/Docker/build/WDQS-frontend/custom-config.json#L9-L15

If you want a fix right now you can simply override this file and point it at your real wiki.
We will add this to the backlog and aim to get a fix into the default config too

**Comment by phucty** [comment]
Thank you very much for the information.
