### ISSUE TITLE
Unable to locate RdfNamespaces.js after install

### ISSUE THREAD

**Issue by paulduchesne** [wmde/wikibase-release-pipeline#328]
I am looking to modify the [RdfNamespaces.js](https://github.com/wikimedia/wikidata-query-gui/blob/master/wikibase/queryService/RdfNamespaces.js) config file, but am finding it is not visible after using the example deployment scripts from this repo. Is this a change in architecture, or am I missing something obvious?

Full list of test commands running on a fresh Ubuntu VM:

~ install docker and docker-compose

> sudo apt update    
> sudo apt install apt-transport-https ca-certificates curl software-properties-common    
> curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
> sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable"
> sudo apt update
> sudo apt install -y docker-ce
> sudo usermod -aG docker ${USER}
> sudo curl -L "https://github.com/docker/compose/releases/download/1.28.5/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
> sudo chmod +x /usr/local/bin/docker-compose
> sudo reboot

~ clone repo and launch

> git clone https://github.com/wmde/wikibase-release-pipeline.git
> cd wikibase-release-pipeline/example/
> cp template.env .env
> cd example
> docker-compose -f docker-compose.yml -f docker-compose.extra.yml up -d

~ navigate to expected location within wdqs-frontend container

> docker exec -it example_wdqs-frontend_1 /bin/sh
> ls -al wikibase/queryService/
> total 12
> drwxr-xr-x    3 root     root          4096 Feb 10 13:53 .
> drwxr-xr-x    3 root     root          4096 Feb 10 13:53 ..
> drwxr-xr-x    2 root     root          4096 Feb 10 13:53 ui

**Comment by paulduchesne** [comment]
Hello @addshore 

The immediate problem that I was facing was that once I have configured my wikibase to HTTPS, the default wd/wdt prefixes cease to work by default and need to be explicitly defined in the query (example [here](https://tinyurl.com/yd884zy2)). My assumption was that these prefixes are defaulting to the namespace in HTTP form.

I did make changes to the files in the /js subdirectory in the hope of modifying the prefixes menu on the sidebar, but noticed that these did not get picked up by the wdqs.

**Comment by addshore** [comment]
The WDQS bakend should have prefixes hardcoded for http and wikidata.
I don't believe there are any default prefixes provided for other wikibases running right now

I believe this would be covered under https://phabricator.wikimedia.org/T205028 and https://phabricator.wikimedia.org/T176190

**Comment by paulduchesne** [comment]
Thank you for clarifying @addshore, I think that we will proceed by looking at building our own image of the query service.

**Comment by addshore** [comment]
No problem, and yes to summarize
1) Right now you will need to build your own image, and have changed these files in the source used to build the image from. You should be able to reuse the Dockerfile with little modification
2) In the future this should be configurable in some way, and then you would not need a custom image. (phab tasks linked)
