### ISSUE TITLE
problems running wikibase on mac M1

### ISSUE THREAD

**Issue by D063520** [wmde/wikibase-release-pipeline#335]
I'm trying to run the pipeline with the standard configuration on a M1 chip by executing 

docker-compose -f docker-compose.yml -f docker-compose.extra.yml up

All containers are running, but blazegraph never starts. It gets stuck at while executing a script. No logs at all. I could not find the reason even after some investigation.

**Comment by addshore** [comment]
I imagine this has something to do with the base image that the wdqs is built on is not designed for the m1 chips / arm.

**Comment by D063520** [comment]
I'm not sure. The base image is FROM ubuntu:xenial

https://github.com/wmde/wikibase-release-pipeline/blob/main/Docker/build/WDQS/Dockerfile

And the container is starting. No problem there. I can even bash inside. But then very strangely he is executing a java --version and never stops.

The wikibase container seams fine, also ES does not seam to complain. The process that never stops is this one:

<img width="1160" alt="Screenshot 2022-04-01 at 14 52 16" src="https://user-images.githubusercontent.com/10883585/161267244-ab1ba241-9925-42cc-999a-da194f3ee250.png">

so a simple java --version if i understand correctly.
.

**Comment by D063520** [comment]
.... I build the image locally with

./build.sh wdqs ./versions/wmde5.env

and replaced image in .env with the one I build.

Working, uffff!!!!

**Comment by addshore** [comment]
Yes, so when you build it locally the local arch will be used for the base image.
The images built and released in CI (and thus on docker hub) will not currently be built for the arm arch.
