### ISSUE TITLE
Configuring and accessing debugging logging output from docker

### ISSUE THREAD

**Issue by ross-spencer** [wmde/wikibase-release-pipeline#340]
Using `docker-compose logs -f` I can see the log of http requests to the server or PHP but there doesn't seem to be any other logging information. For example, when recently getting an error similar to this as a non-admin user: https://phabricator.wikimedia.org/T285959 

Is there a configuration setting required? Or perhaps a different argument to docker-compose?

**Comment by toban** [comment]
Maybe something like this for debugging

```
error_reporting( -1 );
ini_set( 'display_errors', 1 );
$wgShowExceptionDetails = true;
$wgShowSQLErrors = true;
$wgDebugDumpSql  = true;
$wgShowDBErrorBacktrace = true;
$wgDebugLogFile = "/var/log/mediawiki/debug-{$wgDBname}.log";
```

Gives very detailed logs

```
root@be06fa0ea354:/var/www/html# cat /var/log/mediawiki/debug-my_wiki.log 
[DBReplication] ChronologyProtector using store EmptyBagOStuff
[objectcache] MainWANObjectCache using store EmptyBagOStuff


Start request GET /wiki/Main_Page
IP: 172.19.0.1
HTTP HEADERS:
HOST: localhost
USER-AGENT: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:98.0) Gecko/20100101 Firefox/98.0
ACCEPT: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,*/*;q=0.8
ACCEPT-LANGUAGE: en-US,en;q=0.5
```

https://www.mediawiki.org/wiki/Manual:How_to_debug

**Comment by ross-spencer** [comment]
Okay, thanks Tobias. This is a really nice example. I appreciate it, and will keep an eye on the detail here, it looks good. 

Other folks finding this issue might also consider reading the log from the host, e.g. `sudo docker exec <container_id> tail -f /var/log/mediawiki/debug-my_wiki.log` or `sudo docker-compose exec --user=root wikibase tail -f /var/log/mediawiki/debug-my_wiki.log`
