### ISSUE TITLE
Possibility to define custom example queries in query service

### ISSUE THREAD

**Issue by D063520** [wmde/wikibase-release-pipeline#346]
Would it be possible to make the example queries in the query endpoint customisable. We would need this here:

https://github.com/ec-doris/kohesio-backend/issues/161#issuecomment-1119645916

**Comment by addshore** [comment]
As in example queries in the query UI.
There is already configuration for the source of these examples https://github.com/wikimedia/wikidata-query-gui/blob/master/default-config.json#L9-L14

**Comment by D063520** [comment]
Cool thank you! I confirm it works, we implemented it here:

https://query.linkedopendata.eu
