### ISSUE TITLE
Federated and some docker questions

### ISSUE THREAD

**Issue by xploz1on** [wmde/wikibase-release-pipeline#347]
Hello everyone. 
I am currently trying to enable Federated using a docker container. Setting the LocalSettings.php to the docker-compose folder doesnt generated a settings file. I copied the one from the container outside and added the federated lines but the instance after a reboot cant find the settings.
Is there a way to add federated using this docker-compose:
```version: '3.4'

x-common-variables: &wikibase_variables
  DB_SERVER: mysql.svc:3306
  MW_ADMIN_NAME: ${MW_ADMIN_NAME}
  MW_ADMIN_PASS: ${MW_ADMIN_PASS}
  MW_ADMIN_EMAIL: ${MW_ADMIN_EMAIL}
  MW_WG_SECRET_KEY: ${MW_SECRET_KEY}
  # Disable jobs running after requests when wikibase_jobrunner is defined
  MW_WG_JOB_RUN_RATE: 0
  DB_USER: ${DB_USER}
  DB_PASS: ${DB_PASS}
  DB_NAME: ${DB_NAME}
  WIKIBASE_HOST: ${WIKIBASE_HOST}

services:
  wikibase:
    image: "${WIKIBASE_BUNDLE_IMAGE_NAME}"
    links:
      - mysql
    depends_on:
      - mysql
    restart: unless-stopped
    ports:
      - "${WIKIBASE_PORT}:80"
    volumes:
      ## This shares the configuration with jobrunner
      - shared:/var/www/html/:rw

      ## Uncomment this next line to mount your own LocalSettings.php file
      #- ./LocalSettings.php:/var/www/html/LocalSettings.d/LocalSettings.override.php

    networks:
      default:
        aliases:
         - ${WIKIBASE_HOST}
         - wikibase-docker.svc
    environment:
      <<: *wikibase_variables
      WIKIBASE_PINGBACK:
      MW_WG_ENABLE_UPLOADS:

  wikibase_jobrunner:
    image: "${WIKIBASE_BUNDLE_IMAGE_NAME}"
    entrypoint: /bin/bash
    command:  /jobrunner-entrypoint.sh
    links:
      - mysql
    depends_on:
      - mysql
    restart: always
    volumes:
      - shared:/shared/:ro
      - jobrunner-entrypoint.sh:/jobrunner-entrypoint.sh
    networks:
      default:
        aliases:
          - wikibase-jobrunner.svc
    environment:
      <<: *wikibase_variables
      MAX_JOBS: ${MAX_JOBS}

  mysql:
    image: "${MYSQL_IMAGE_NAME}"
    restart: unless-stopped
    volumes:
      - mediawiki-mysql-data:/var/lib/mysql
    environment:
      # CONFIG - Change the default values below (should match values passed to wikibase)
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
    networks:
      default:
        aliases:
         - mysql.svc

volumes:
  shared:
  mediawiki-mysql-data:
```
In this case i commented LocalSettings. Thanks!

**Comment by xploz1on** [comment]
Thank you so much. I was settings the file inside LocalSettings.php folder for some reason.

![Screenshot from 2022-05-18 10-48-28](https://user-images.githubusercontent.com/13008386/169071050-b753da7f-94af-4e4d-aa36-70406b7d3dbc.png)

**Comment by xploz1on** [comment]
@ross-spencer Maybe you can help me (again).
I have a fresh server and i have setup nginx proxy manager and been testing wikibase.
Looks like wikibase install with extras uses its own proxy. My question is what i need to change to make everything work.
Adding wikibase to nginx proxy gives me an error because it forwards to /wiki/Main_Page
I have not much experience setting up containers with this kind of setup. Also wondering how to add seemingly QuickStatements and QueryService. Maybe there is modifications to the docker-compose and .env i need to make/add. Hopefully you or anyone else can give me a hand to get this working. Thanks!

**Comment by ross-spencer** [comment]
@xploz1on glad you're getting a bit further with this. With regard to the additional configuration, I couldn't help beyond more than [what the docs offer](https://github.com/wmde/wikibase-release-pipeline/tree/main/example#running-additional-services) at this point. I'm using an older version of this repo, with everything pretty default, bar a couple of volumes for data, extensions etc.

Notably, you need to make sure the extras docker-compose file is added during startup: `docker-compose -f docker-compose.yml -f docker-compose.extra.yml up` and the `extras.sh` volume is uncommented in the primary docker-file. 

Perhaps like you say, someone else knows, or perhaps there are some additional details needed?

**Comment by xploz1on** [comment]
Everything works but i have a problem with my nginx proxy and the wikibase own proxy. Even setting the web site name variable to my own doesn't work haha. Web site still says wikibase-docker.
Now those extra are supposed to be run as a separated instances? The whole setup works like i said before. But making it wiork with my nginx reverse proxy gives errors or wont load in the case of QS..
Is there another variable or env for web site name? 
![Screenshot from 2022-05-20 07-46-24](https://user-images.githubusercontent.com/13008386/169521890-881d27bb-8037-445e-b664-3748dd4b417d.png)
 
I am trying to understand the docs and any online resource i can to make all work with docker.

**Comment by bmcginnis827** [comment]
> Is there another variable or env for web site name?

Add this in your LocalSettings.php you mount in the docker-compose file:

`/*******************************/
/* Wiki Name */
/*******************************/
$wgSitename = 'Prosop Wiki';`

**Comment by addshore** [comment]
> I will say, the documentation for running this on a domain is very lacking.

The basic environment variables only provide basic configuration.
For any production / customised installation, you probably want your own LocalSettings file with MediaWiki settings configured.

See https://www.mediawiki.org/wiki/Manual:$wgServer
https://www.mediawiki.org/wiki/Manual:$wgSitename
