### ISSUE TITLE
No Wikibase docker image for 1.37

### ISSUE THREAD

**Issue by despens** [wmde/wikibase-release-pipeline#350]
The version used in the docker build process currently is still wikibase/wikibase:1.36.3-wmde.5 while Wikibase.cloud uses 1.37 and Wikidata uses 1.38.

Having 1.37 published as a docker image would be helpful.

**Comment by Georgina-Burnett-WMDE** [comment]
Hi Dragan, 

Per our [announcement](https://lists.wikimedia.org/hyperkitty/list/wikibaseug@lists.wikimedia.org/thread/HRLNLDSEJOYJE7VSLEY2UOHYF4OUDL3B/) on April 12, the focus on Wikibase.cloud currently means that our Wikibase releases are delayed. The plan continues to be to do the next feature release in the Northern Hemisphere summer. As soon as we have any more specific information, we will announce it on-list. Longer term, we intend to ensure Wikibase releases are done in sync with MediaWiki. 

Thanks,
Georgina

**Comment by addshore** [comment]
https://lists.wikimedia.org/hyperkitty/list/wikibaseug@lists.wikimedia.org/thread/RWS6EV7SHFNOD6KKQ6JA7RUW4TEXSXN5/
