### ISSUE TITLE
How are folks configuring Wikibase using nginx as a reverse proxy?

### ISSUE THREAD

**Issue by ross-spencer** [wmde/wikibase-release-pipeline#352]
Hi all. I am looking for advice running nginx revere proxy alongside the example repository here. I have included an excerpt from my `nginx.conf` file below. Once I had the server stood up, I found a number of redirects in Wikimedia were not working, and so the config below helps to route those. I don't think they are perfect, and I haven't "captured" all the different routes, e.g. statements still seem a bit difficult to configure. 

My questions are thus:

a) am I on the right path?
b) how are others doing this? and do they have any advice/examples they can share?

```conf

    server {

       server_name test.site.io;

       rewrite ^(\/entity\/)(Q\d)$ /wiki/Special:EntityData/$2 last;
       rewrite ^(\/entity\/)(P\d)$ /wiki/Special:EntityData/$2 last;
       rewrite ^(\/prop\/)(P\d)$ /wiki/Property:$2 last;
       rewrite ^(\/prop\/.*\/)(P\d)$ /wiki/Property:$2 last;

       location /proxy/ {
          proxy_pass http://localhost:8834/proxy/;
       }
       location /wdqs/ {
          proxy_pass http://localhost:8834/;
       }
       location / {
          proxy_pass http://localhost:8832/;
          # add_header corrects for (blocked:mixed-content) in Ajax requests.
          add_header Content-Security-Policy upgrade-insecure-requests;
       }
```

**Comment by addshore** [comment]
Hey ross,

Are you using the wmde released docker images or something else?

For the reverse proxy itself, I wouldn't include things such as the `/entity` redirects, I'd simply make sure that `/w` and `/wiki` or whatever you have configured point to the MediaWiki/Wikibase host / service.
I would then have `/entity` rewrites on this MediaWiki/Wikibase host / service.

Also if you are pointing most traffic to mediawiki, and just wanting other locations for other services you may find looking at the old wbstack.com configuration will help
https://github.com/wbstack/deploy/blob/1f5853eb832e40e3a39c7a9e54ab9a3bf555c9d0/k8s/helm/platform-nginx/nginx.conf
wikibase.cloud has a similar config but this is not yet in a public repository
```
       location /proxy/ {
          proxy_pass http://localhost:8834/proxy/;
       }
```

Not sure what this bit is for in your proxy setup?

```
       location /wdqs/ {
          proxy_pass http://localhost:8834/;
       }
```

Probably a more typical choice for a path for wdqs would be `/query`
