### ISSUE TITLE
Installing extensions

### ISSUE THREAD

**Issue by yoavnash** [wmde/wikibase-release-pipeline#393]
How does one install extensions under the set up given in the [example folder](https://github.com/wmde/wikibase-release-pipeline/tree/main/example)?
For example, I try to install this extension: https://github.com/OpenSemanticLab/mediawiki-extensions-InteractiveSemanticGraph

**Comment by schelv** [comment]
One way to do it is the following. (it works but isn't pretty) 
Downloading the extension and then mounting the directory into the running containers with works.
In the `docker-compose.json` the extension directory should be mounted to both the `wikibase` service and the `wikibase_jobrunner` service:
```
services:
  wikibase:
    ...
    volumes:
      ...
      - ./LocalSettings.php:/var/www/html/LocalSettings.d/LocalSettings.override.php
      - ${EXTENSION_PATH}:/var/www/html/extensions/<extension dir name>
      ...
   wikibase_jobrunner:
    ...
    volumes:
      ...
      - ./LocalSettings.php:/var/www/html/LocalSettings.d/LocalSettings.override.php
      - ${EXTENSION_PATH}:/var/www/html/extensions/<extension dir name>
```

**Comment by yoavnash** [comment]
Thank you!

**Comment by addshore** [comment]
When using the container images you want to do one of the following:

1) Build on top of the container images that are created as part of suite, adding the extensions that you want/need
2) Just mount files into the containers at run time as described above using docker-compose

If there are extensions that are generally accepted to be part of a default wikibase experience we can look at adding them to the bundle container image
