### ISSUE TITLE
 jobrunner-entrypoint.sh gets Windows line endings so the container does not run on Windows. 

### ISSUE THREAD

**Issue by matssk** [wmde/wikibase-release-pipeline#570]
The docker container for the jobrunner does not work on Windows. There is an issue with line endings . Editing the file jobrunner-entrypoint.sh and changing the line endings to Unix fixes the issue. I had not edited the file prior to running it, but perhaps the process of copying it from wikibase-release-pipeline\example to wbdocker causes the issue?

**Steps to reproduce:**

Run the following commands on Windows:

git clone https://github.com/wmde/wikibase-release-pipeline
cd wikibase-release-pipeline
git checkout tags/wmde.14

mkdir wbdocker
cp -r example/* ./wbdocker
cd ./wbdocker
mv template.env .env

docker compose up

**The following errors will show**

wikibase-jobrunner-1  | /jobrunner-entrypoint.sh: line 12: $'\r': command not found
wikibase-jobrunner-1  | /jobrunner-entrypoint.sh: line 13: syntax error near unexpected token `$'{\r''
'ikibase-jobrunner-1  | /jobrunner-entrypoint.sh: line 13: `kill_runner() {
wikibase-jobrunner-1  | /jobrunner-entrypoint.sh: line 2: $'\r': command not found
wikibase-jobrunner-1  | /jobrunner-entrypoint.sh: line 5: $'\r': command not found
")syntax error: invalid arithmetic operator (error token is "
")syntax error: invalid arithmetic operator (error token is "
wikibase-jobrunner-1  | wait-for-it.sh: waiting for mysql.svc:3306 without a timeout
wikibase-jobrunner-1  | wait-for-it.sh: mysql.svc:3306 is available after 0 seconds
wikibase-jobrunner-1  | sleep: invalid time interval '1\r'
wikibase-jobrunner-1  | Try 'sleep --help' for more information.
")syntax error: invalid arithmetic operator (error token is "
")syntax error: invalid arithmetic operator (error token is "

**Steps to fix**
Open jobrunner-entrypoint.sh in a text editor like Notepad++ and change the line endings to LF or run dos2unix jobrunner-entrypoint.sh in gitbash.

**Comment by rti** [comment]
Hi @matssk,

Thanks for your report. Unfortunately, we do not support windows at the moment. That being said, people are reporting success in running the most recent versions in windows environments. Maybe you want to give [deploy-3](https://github.com/wmde/wikibase-release-pipeline/blob/deploy-3/deploy/README.md) a try?

Best,
Robert

**Comment by rti** [comment]
@matssk Just found this issue https://github.com/docker/for-win/issues/1340. I think this could be related. The workaround is here: https://github.com/docker/for-win/issues/1340#issuecomment-716941493.

**Comment by rti** [comment]
@matssk there is also `autocrlf` in git which could be related.

https://git-scm.com/book/en/v2/Customizing-Git-Git-Configuration#_core_autocrlf

**Comment by rti** [comment]
Closing this now. Feel free to reopen for further clarification or follow up.
