### ISSUE TITLE
Add option to remove the query builder since it is not adapted to wikibase yet

### ISSUE THREAD

**Issue by D063520** [wmde/wikibase-release-pipeline#664]
I would suggest to add an environment variable in the docker compose of the query service to remove this:

<img width="1726" alt="Screenshot 2024-04-23 at 21 36 00" src="https://github.com/wmde/wikibase-release-pipeline/assets/10883585/0818bf45-a23e-464e-9f34-279030353a00">

**Comment by rti** [comment]
We just merged a workaround. The link will now send the user to the code repo of the query builder.

Closing this now, feel free to reopen for a follow up.
