### ISSUE TITLE
Example configuration doesn't build in branch «tallinn»

### ISSUE THREAD

**Issue by olea** [wmde/wikibase-release-pipeline#672]
Procedure:

- git clone git@github.com:wmde/wikibase-release-pipeline.git
- cd wikibase-release-pipeline/
- git checkout tallinn
- cd example/
- docker compose --env-file template.env up --wait

One container doesn't build and error message is:
> dependency failed to start: container wikibase-suite-example-wikibase-1 is unhealthy

Checking logs: 
- docker logs wikibase-suite-example-wikibase-1
> MW_ADMIN_NAME is required but isn't set. You should pass it to docker. See: https://docs.docker.com/engine/reference/commandline/run/#set-environment-variables--e---env---env-file

After studying the problem it's found because variables have been renamed (and some deleted)  in docker-compose.yml. This happens also with the _wikibase-suite-example-quickstatements-1_ container.

With this patch the configuration builds up as expected:

``` diff
diff --git a/example/docker-compose.yml b/example/docker-compose.yml
index ecce58f..5161495 100644
--- a/example/docker-compose.yml
+++ b/example/docker-compose.yml
@@ -19,12 +19,20 @@ services:
       - quickstatements-config:/quickstatements/data
     environment:
       SETUP_MW_ADMIN_NAME: ${SETUP_MW_ADMIN_NAME}
+      MW_ADMIN_NAME: ${SETUP_MW_ADMIN_NAME}
       SETUP_MW_ADMIN_PASS: ${SETUP_MW_ADMIN_PASS}
+      MW_ADMIN_PASS: ${SETUP_MW_ADMIN_PASS}
       SETUP_MW_ADMIN_EMAIL: ${SETUP_MW_ADMIN_EMAIL}
+      MW_ADMIN_EMAIL: ${SETUP_MW_ADMIN_EMAIL}
+      MW_WG_SECRET_KEY: "farfollas"
       SETUP_DB_SERVER: mysql:3306
+      DB_SERVER: mysql:3306
       SETUP_DB_USER: ${SETUP_DB_USER}
+      DB_USER: ${SETUP_DB_USER}
       SETUP_DB_PASS: ${SETUP_DB_PASS}
+      DB_PASS: ${SETUP_DB_PASS}
       SETUP_DB_NAME: ${SETUP_DB_NAME}
+      DB_NAME: ${SETUP_DB_NAME}
       MW_WG_SERVER: http://${WIKIBASE_PUBLIC_HOST}
       MW_WG_ENABLE_UPLOADS: false
       WIKIBASE_PINGBACK: false
@@ -177,6 +185,8 @@ services:
     volumes:
       - quickstatements-config:/quickstatements/data
     environment:
+      QS_PUBLIC_SCHEME_HOST_AND_PORT: http://${QUICKSTATEMENTS_PUBLIC_HOST}
+      WB_PUBLIC_SCHEME_HOST_AND_PORT: http://${WIKIBASE_PUBLIC_HOST}
       WB_PROPERTY_NAMESPACE: 122
       WB_PROPERTY_PREFIX: "Property:"
       WB_ITEM_NAMESPACE: 120
 
```

**Comment by addshore** [comment]
It sounds like you have found the / a solution?!

Do you fancy making a PR? :)

**Comment by tarrow** [comment]
I imagine @rti can confirm but I imagine it might not be designed to work. Looking at https://github.com/wmde/wikibase-release-pipeline/pull/671 makes it seem like this is just a temporary branch that was never designed to be more than a draft.

**Comment by darthmon** [comment]
Hey,  @olea has been trying out this branch out and the containers would not come up. We looked at it together and found this out. He then edited it and tried it out and the containers would start. He asked me if he should note this in the repo and I said "yes, please!"

I would recommend not to do that change just now. He still could not get the wikibase to work so we should check it out tomorrow together and then decide which changes to do.

**Comment by rti** [comment]
It is true, this branch is definitely meant as a demo branch only, as the state it represents is currently in development.

@olea the variable changes you noticed are intentional. In order to make `docker-compose.yml` of this branch work, the `.env` file needs to point to the following images:
```
WIKIBASE_SUITE_WIKIBASE_BUNDLE_IMAGE_URL=ghcr.io/wmde/wikibase/wikibase-bundle:dev-tallinn
WIKIBASE_SUITE_WDQS_IMAGE_URL=ghcr.io/wmde/wikibase/wdqs:dev-tallinn
WIKIBASE_SUITE_WDQS_FRONTEND_IMAGE_URL=ghcr.io/wmde/wikibase/wdqs-frontend:dev-tallinn
WIKIBASE_SUITE_WDQS_PROXY_IMAGE_URL=ghcr.io/wmde/wikibase/wdqs-proxy:dev-tallinn
WIKIBASE_SUITE_ELASTICSEARCH_IMAGE_URL=ghcr.io/wmde/wikibase/elasticsearch:dev-tallinn
WIKIBASE_SUITE_QUICKSTATEMENTS_IMAGE_URL=ghcr.io/wmde/wikibase/quickstatements:dev-tallinn
MARIADB_IMAGE_URL=mariadb:10.11
```

An alternative would be to try our latest stable release (the tag `wmde.20`) for now.

**Comment by olea** [comment]
> An alternative would be to try our latest stable release (the tag wmde.20) for now.

fine

Should I close this report?

**Comment by rti** [comment]
Does `wmde.20` work for you?

**Comment by olea** [comment]
> Does `wmde.20` work for you?

Containers got up but found a database error when accessing Wikibase. I'll look for the time to get again into this. Hopefully at the end of the week. 

Thanks!
