### ISSUE TITLE
Right way to add Wikibase extensions to the Wikibase Docker ?

### ISSUE THREAD

**Issue by aurelien23** [wmde/wikibase-release-pipeline#697]
Hello,

We're using Docker Wikibase in this repository: 
https://github.com/abes-esr/movies-docker

We use Wikibase and Wikibase-jobrunner services configured from this other repository, which contains a Dockerfile: https://github.com/abes-esr/movies-wikibase/blob/develop/Dockerfile
Extensions are added to this Dockerfile.

We have a problem with the maintenance of the wikibase container, because it uses a shared volume: when we add a new extension to the Dockerfile, it is not added to the already existing shared volume.

What do you think is the right way to add Wikibase extensions to the Wikibase Docker installation, please?

Best regards,

**Comment by Superraptor** [comment]
Not an answer for sure, but I've documented my attempts so far in this Phabricator ticket: https://phabricator.wikimedia.org/T372599

**Comment by rti** [comment]
Hi @aurelien23,

Thanks a lot for approaching us.

The shared volume you mention is a relict from `wikibase-release-pipeline` history and the `movies-docker` might still use the idea. The current versions we ship, e.g. [deploy-3](https://github.com/wmde/wikibase-release-pipeline/tree/deploy-3) got rid of this structure. It created several unwanted side-effects. I'd really like to encourage you to checkout our `deploy-3`, find the documentation here: https://github.com/wmde/wikibase-release-pipeline/blob/deploy-3/deploy/README.md

There is no official way to add extensions at the moment. But I added a workaround solution to the ticket @Superraptor mentioned: https://phabricator.wikimedia.org/T372599. Please note that this guide is already using our `main` branch, that prepares for the upcoming versions.

Hope that helps,
Best,
Robert

**Comment by rti** [comment]
Will close this now. Feel free to reopen if you have further questions.
