### ISSUE TITLE
Limiting IP address range in docker-compose.yml

### ISSUE THREAD

**Issue by Superraptor** [wmde/wikibase-release-pipeline#746]
I've run into an issue (documented here: https://unix.stackexchange.com/questions/781514/running-apt-get-update-in-debian-docker-container-hangs-on-installing-bookworm?noredirect=1#comment1496120_781514) wherein using `apt-get update` (and similar commands) was seemingly failing at random. This was extremely difficult to diagnose, as it was causing very itermittent issues and spun out no error messages.

The culprit, I'm 99% sure, is that sometimes spinning up a Wikibase instance will put `wbdocker-wikibase-1` into the IP range `192.168.*.*` (i.e. 192.168.144.6 or 192.168.128.6). It works when the IP range is different, such as `172.18.*.*` (i.e. 172.18.0.5). I can't seem to find a way that `docker-compose.yml` will accept limiting containers to a particular IP address range.

Is there a recommended solution in order to be able to do so?

**Comment by rti** [comment]
Hi @Superraptor,

Interesting issue. Thanks for reporting this.

I think the relevant docker compose options are described here and here:
 - https://docs.docker.com/compose/networking/#specify-custom-networks
 - https://docs.docker.com/reference/compose-file/services/#ipv4_address-ipv6_address

Hope that helps,
Best,
Robert

**Comment by Superraptor** [comment]
Yes! That helps! (I haven't had this issue since the release pipeline was updated though, so I can't test the solution really-- I'll go ahead and close!)
