### ISSUE TITLE
Deploying the Wikibase Release Pipeline Locally

### ISSUE THREAD

**Issue by Superraptor** [wmde/wikibase-release-pipeline#747]
So it appears I've been using an older version of the pipeline, so I've been attempting to start from scratch with the newer directions to spin up a localhost Wikibase.

I'm using the defaults, and all of the Docker containers are healthy and running. The WQS frontend appears correct at `http://localhost:8834/` and QuickStatements appears at `http://localhost:8840/``. However, the Wikibase itself redirects from `http://localhost:8880/` to `https://wikibase.example.com/wiki/Main_Page`.

Reading the docs, I see that I need to "[c]onfigure those domains in `/etc/hosts` to make them resolve to `127.0.0.1`". I assume this means I need to enter the Docker container (`wbs-deploy-wikibase-1`) and look at `/etc/hosts`. I open the file to find the following (by default):

```
127.0.0.1          localhost
::1     localhost ip6-localhost ip6-loopback
fe00::0 ip6-localnet
ff00::0 ip6-mcastprefix
ff02::1 ip6-allnodes
ff02::2 ip6-allrouters
192.168.16.5      290910c15098
```

So it would seem that `/etc/hosts/` is already configured to resolve to `127.0.0.1`? Any help with this would be much, much appreciated!

**Comment by Superraptor** [comment]
Ok-- so nothing is needed at all with `etc/hosts`. You just have to change `WIKIBASE_PUBLIC_HOST` in `.env` to `localhost`. That's it! Closing this, but I still think the documentation should be updated to reflect this.

**Comment by rti** [comment]
I put some details here https://phabricator.wikimedia.org/T372177
