### ISSUE TITLE
Wikibase Homepage not available 

### ISSUE THREAD

**Issue by ravikcs** [wmde/wikibase-release-pipeline#760]
The proxy forwards traffic to port 80 of the VM.

According to the docker-compose.yml configuration, the reverse proxy (Traefik) listens on port 80 of the VM and appears to handle all traffic, including SSL encryption.

Additionally, the application (Wikibase) is also configured to listen on port 80. This raises the question: should the application be directly listening on the same port as the reverse proxy?

In the browser, we encounter a "Too many redirects" error. Upon investigating the logs using docker logs, we observe issues with Let's Encrypt SSL certificate creation, likely due to the setup behind the external proxy. However, since Traefik manages SSL certificate creation and listens on port 80, it should theoretically handle the process correctly with Let's Encrypt.

**Comment by rti** [comment]
Hi @ravikcs,

Thanks a lot for contacting us.

> should the application be directly listening on the same port as the reverse proxy?

It is true that both, the wikibase container and the reverse proxy container listen on port 80. But this happens on the virtual network interfaces of the containers, both have their own, so there is no conflict. Only the [reverse proxy port 80 gets forwarded to the host machines port 80](https://github.com/wmde/wikibase-release-pipeline/blob/8946bc98073a9a17fabb4203ba8a24f09fa071f2/deploy/docker-compose.yml#L189) and is therefore available to the outside world. The wikibase container port 80 is only available internally to the virtual network of the docker compose stack.

> In the browser, we encounter a "Too many redirects" error.

> issues with Let's Encrypt SSL certificate creation

I suspect this could be two different things. Could you please share the logs, your `.env` file, and any further adjustments you might have done?

For Traefik  to successfully obtain certificates from LetsEncrypt, it needs:
 - A public IP address
 - A domain name registered in public DNS and set in `.env` `*_PUBLIC_HOST`
 - The domain names DNS A record pointing to the public IP address
 - A valid E-Mail address set in `.env` `MW_ADMIN_EMAIL`

Best,
Robert

**Comment by ravikcs** [comment]
Hello @rti ,

Thanks for the follow-up. I have attached the .env file for your reference. Also, the logs I get for Traefik:

2024-09-05T08:05:09Z ERR Unable to obtain ACME certificate for domains error="cannot get ACME client ACME challenge not specified, please select TLS or HTTP or DNS Challenge" ACME CA=https://acme-v02.api.letsencrypt.org/directory acmeCA=https://acme-v02.api.letsencrypt.org/directory domains=["metabelgica.ilabt.imec.be"] providerName=letsencrypt.acme routerName=wikibase@docker rule=Host(`metabelgica.ilabt.imec.be`)

[env_file.txt](https://github.com/user-attachments/files/16905223/env_file.txt)

**Comment by rti** [comment]
Hi @ravikcs,

Thanks a lot for the information! 

You need to specify three different hostnames in your .env file. `WIKIBASE_PUBLIC_HOST`,
 `WDQS_FRONTEND_PUBLIC_HOST` and `QUICKSTATEMENTS_PUBLIC_HOST` all need to be distinct, but can be subdomains. E.g. `query.metabelgica.ilabt.imec.be` should work. But of cause you need to add the respective DNS records as well.

Traefik complaining about the challenge type missing is weird. It is clearly stated here: https://github.com/wmde/wikibase-release-pipeline/blob/66d59fafdbc701bc0694120564733d7ccd116cbf/deploy/docker-compose.yml#L189

Maybe making the domain names distinct prevents Traefik from getting confused and already helps?

Did you make any other changes besides the `.env` file?

Best,
Robert

**Comment by rti** [comment]
Hi @SvenLieber,

Thanks for your post.

> Does this need to be domains? I was wondering if we could have something like metabelgica.ilabt.imec.be/query, but I remember some issues with Let's Encrypt then as well.

Yes, at the moment this can only be domain names. Running from a sub folder is unfortunately not trivial, but definitely worth a feature request, ideally at https://phabricator.wikimedia.org/maniphest/task/edit/form/125/

Yes, DNS seems properly forwarding to `idlab.proxy.ilabt.imec.be` which is probably the reverse proxy you mentioned.

The port mapping change is probably unrelated. I'd actually suggest to not use the `main` branch. This is where our development happens at the moment. Better to check out `deploy-3` which contains our latest stable release.

Best,
Robert

**Comment by SvenLieber** [comment]
Hi @rti ,

the ICT department responsible for our proxy solved the issue.
Apparently their proxy does exactly what `traefik` is supposed to do. So they created new DNS records, configured their proxy, configured SSL correctly and we removed all `traefik` parts from the config.

Best,
Sven
