### ISSUE TITLE
Is it possible to use RaiseWikibase with current version of Wikibase Suite?

### ISSUE THREAD

**Issue by megamattc** [wmde/wikibase-release-pipeline#768]
Hello,  

I was wondering if anyone has found out how to use RaiseWikibase with the current version of Wikibase Suite?  The RaiseWikibase repository contains code for setting up an older version of Wikibase, but I am unsure how the former draws on the latter. The documentation seems to assume you just work within the Wikibase constructed by the RaiseWikibase code itself. I am unsure how one could use RaiseWikibase for a Wikibase instance not constructed by that older code....

**Comment by rti** [comment]
Hi @megamattc,

Unfortunately, we currently do not officially support RaiseWikibase.

I think it is worth a try though. The database schema is mentioned in the [Stable Interface Policy](https://www.wikidata.org/wiki/Wikidata:Stable_Interface_Policy#Stable_Public_APIs) in the paragraph of "Stable Public APIs" acknowledging the direct use of the DB schema. Looking at the [diff of the DB schema documentation](https://www.mediawiki.org/w/index.php?title=Wikibase/Schema&diff=cur&oldid=3701001) from "before 1.35 release" (the version RaiseWikibase was [apparently](https://github.com/UB-Mannheim/RaiseWikibase/blob/0507494c8c40ca1f1bae0b2bce6dfba35090c1c2/docs/quickstart/wikibase-docker.md) tested with) to today, it is quite likely that RaiseWikibase could still work... unless it relies on tables already deprecated back then.

If you give it a try I would love to hear what you found out.

Hope that helps a bit,
Best,
Robert

**Comment by rti** [comment]
Closing this now due to inactivity.

Feel free to reopen if you have new information.
