### ISSUE TITLE
[WDQS] PREFIX not aligned with concept URI

### ISSUE THREAD

**Issue by fdeuze** [wmde/wikibase-release-pipeline#798]
Setup:
Using WDQS:2 (wdqs0.3.142 from Oct 28, 2024) which solve correctly the issue to set the WIKIBASE_CONCEPT_URI required in wdqs-updater container (Note: However fix is needed in docker-compose.xml to set the correct version [here](https://github.com/wmde/wikibase-release-pipeline/blob/fe7f8918caf016d663a65827bd4efb7deda768f8/deploy/docker-compose.yml#L107C12-L107C27))

Issue:
The PREFIX in SPARQL query is not using the correct concept URI in wdqs container.
Indeed, setting the log "com.bigdata.rdf.sail.webapp.BigdataRDFContext" to level "debug", messages show:
PREFIX wdt: <http://wikibase/prop/direct/>
PREFIX wd: <http://wikibase/entity/>

instead of something like:

PREFIX wdt: <https://concept_uri/prop/direct/>
PREFIX wd: <https://concept_uri/entity/>

Recreation:
Any SPARQL query using prefix like wd or wdt from wdqs-fontend container UI.
For example this query doesn't return anything:
select *
where 
{
  ?s ?p wd:Q1
}
LIMIT 10

whereas this query return the expected result:
select *
where 
{
  ?s ?p <https://concept_uri/entity/Q1>
}
LIMIT 10

**Comment by rti** [comment]
Hi,

Thanks a lot for reaching out!

> However fix is needed in docker-compose.xml to set the correct version [here](https://github.com/wmde/wikibase-release-pipeline/blob/fe7f8918caf016d663a65827bd4efb7deda768f8/deploy/docker-compose.yml#L107C12-L107C27)

Thanks for pointing that out. We released this as a fix to deploy yesterday https://github.com/wmde/wikibase-release-pipeline/releases/tag/deploy%403.0.3

We will have a look into the prefixes issue!

**Comment by rti** [comment]
Closing this as the PR got merged to `main`
